const { chromium } = require('C:/Users/Sadeq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path = require('path');
const fs = require('fs');
(async () => {
  const output = path.resolve(process.argv[2] || '../../Exchange-Universe-Review');
  fs.mkdirSync(output, {recursive:true});
  const browser = await chromium.launch({headless:true,executablePath:'C:/Users/Sadeq/AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe'});
  const page = await browser.newPage({viewport:{width:1500,height:1050}, deviceScaleFactor:1});
  const issues=[];
  page.on('pageerror',e=>issues.push(e.message));
  await page.goto('http://127.0.0.1:4888/', {waitUntil:'domcontentloaded'});
  await page.waitForSelector('#comparison_chart canvas', {timeout:30000});
  await page.waitForFunction(()=>document.querySelector('#comparison_chart canvas'),{timeout:15000});
  await page.waitForFunction(()=>{const m=window.HTMLWidgets?.find('#world_map')?.getMap();return m&&Object.values(m._layers).filter(l=>l.getLatLngs).length>200},{timeout:15000});
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  console.log('Desktop text:',(await page.locator('body').innerText()).slice(0,4000));
  console.log('Chart state:',await page.evaluate(()=>({series:echarts.getInstanceByDom(document.getElementById('comparison_chart')).getOption().series.map(x=>({name:x.name,points:x.data.length})), mapPaths:document.querySelectorAll('.leaflet-interactive').length,errors:Array.from(document.querySelectorAll('.shiny-output-error')).map(x=>x.textContent)})));
  await page.locator('#theme_toggle').click();
  await page.waitForTimeout(700);
  await page.screenshot({path:path.join(output,'desktop-dark.png'),fullPage:true});
  await page.locator('#theme_toggle').click();
  await page.setViewportSize({width:390,height:844});
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForSelector('#comparison_chart canvas',{timeout:30000});
  await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
  console.log('Mobile:',await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,settingsOpen:document.getElementById('settings_panel').open,errors:Array.from(document.querySelectorAll('.shiny-output-error')).map(x=>x.textContent)})));
  console.log('JavaScript errors:',issues);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
