const {chromium}=require('C:/Users/Sadeq/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict');
const fs=require('fs');
const path=require('path');
(async()=>{
 const out=path.resolve('../Exchange-Universe-Review');fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:'C:/Users/Sadeq/AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe'});
 const context=await browser.newContext({viewport:{width:1500,height:1000},permissions:['clipboard-read','clipboard-write']});
 const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:4888/',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>document.querySelector('#comparison_chart canvas'),{timeout:30000});
 await page.waitForFunction(()=>window.HTMLWidgets?.find('#world_map')?.getMap()?.layerManager?.getLayer('shape','JPN'),{timeout:30000});
 console.log('Initial errors:',await page.locator('.shiny-output-error').allTextContents());
 console.log('Layout:',await page.evaluate(()=>({page:document.documentElement.scrollWidth,sidebar:[document.querySelector('.sidebar').clientHeight,document.querySelector('.sidebar').scrollHeight],workspace:[document.querySelector('.workspace').clientHeight,document.querySelector('.workspace').scrollHeight]})));
 await page.screenshot({path:path.join(out,'refined-explore-dark.png')});
 const before=await page.evaluate(()=>({main:document.querySelector('.workspace').scrollTop,page:scrollY}));
 for(const id of ['sidebar_period','sidebar_saved'])await page.locator('#'+id+' > summary').click();
 await page.locator('.sidebar').hover();await page.mouse.wheel(0,700);await page.waitForTimeout(150);
 const after=await page.evaluate(()=>({main:document.querySelector('.workspace').scrollTop,page:scrollY,sidebar:document.querySelector('.sidebar').scrollTop}));
 assert(after.sidebar>0);assert.equal(after.main,before.main);assert.equal(after.page,before.page);
 console.log('Independent sidebar scrolling: PASS');
 // Click Japan through the browser's pointer at its rendered map coordinates.
 const japan=await page.evaluate(()=>{const map=HTMLWidgets.find('#world_map').getMap();const point=map.latLngToContainerPoint(L.latLng(36,138));const box=document.getElementById('world_map').getBoundingClientRect();return {x:box.x+point.x,y:box.y+point.y};});
 await page.mouse.click(japan.x,japan.y);
 await page.waitForSelector('[data-focus-currency="JPY"]');
 assert.equal(await page.locator('#country_detail strong').innerText(),'Japan');console.log('Country click auto-adds JPY: PASS');
 await page.locator('#tab_convert').click();
 await page.waitForSelector('.conversion-value');assert(await page.locator('#view_explore').isHidden());
 const directRate=Number((await page.locator('#conversion_note').innerText()).match(/1 EUR = ([\d,.]+) HUF/)[1].replaceAll(',',''));
 const convertedAmount=async()=>Number((await page.locator('.conversion-value').innerText()).match(/[\d,.]+/)[0].replaceAll(',',''));
 await page.locator('[data-amount="10000"]').click();await page.waitForFunction(()=>document.querySelector('.conversion-equation').textContent.includes('10,000.00'));
 // The explanatory rate is displayed to four decimals; conversion retains raw precision.
 assert(Math.abs(await convertedAmount()-10000*directRate)<=.51);console.log('Convert view + quick amounts: PASS');
 await page.locator('#swap').click();await page.waitForFunction(()=>document.querySelector('.conversion-equation').textContent.includes('HUF'));
 assert(Math.abs(await convertedAmount()-10000/directRate)<.01);await page.locator('#swap').click();
 console.log('Inverse conversion + swap: PASS');
 await page.screenshot({path:path.join(out,'refined-convert.png')});
 await page.locator('#tab_data').click();await page.waitForSelector('#summary_table tbody tr');
 assert(await page.locator('#summary_table thead').first().innerText().then(t=>t.includes('Low date')));console.log('Detailed comparison columns: PASS');
 await page.screenshot({path:path.join(out,'refined-data-summary.png')});
 await page.locator('input[name=data_mode][value=history]').check({force:true});
 await page.waitForFunction(()=>document.querySelector('#summary_table thead')?.textContent.includes('Daily strength'));
 await page.waitForTimeout(200);console.log('History records:',await page.locator('#data_stats').innerText());
 const href=await page.locator('#download_csv').getAttribute('href');const csv=await context.request.get(new URL(href,page.url()).href);assert.equal(csv.status(),200);assert.match(await csv.text(),/Daily strength %/);
 fs.writeFileSync(path.join(out,'refined-history.csv'),await csv.body());
 await page.screenshot({path:path.join(out,'refined-data-history.png')});
 await page.locator('input[name=data_mode][value=quotes]').check({force:true});
 await page.waitForFunction(()=>document.querySelector('#summary_table thead')?.textContent.includes('Mapped places'));
 await page.waitForTimeout(200);assert.match(await page.locator('#data_stats').innerText(),/174/);console.log('All 174 quotes: PASS');
 await page.locator('#save_view').click();await page.locator('#view_name').fill('Atlas review');await page.locator('#confirm_save').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('exchange-universe.v2.views')||'[]').length===1);
 await page.locator('#share').click();await page.waitForFunction(()=>document.getElementById('local_toast').textContent==='Comparison link copied.');
 const shared=await page.evaluate(()=>navigator.clipboard.readText());assert.match(shared,/#data$/);assert.match(shared,/compare=.*JPY/);
 await page.goto(shared);await page.waitForSelector('#summary_table tbody tr');assert.equal(await page.locator('#tab_data').getAttribute('aria-selected'),'true');
 console.log('Saved comparison + shared view/selection restoration: PASS');
 await page.locator('#tab_explore').click();await page.locator('input[name=chart_dimension][value="3d"]').check({force:true});
 await page.waitForFunction(()=>document.getElementById('strength_3d')?.data?.length>0,{timeout:30000});
 await page.waitForTimeout(600);
 await page.locator('[data-legend-currency="GBP"]').click();await page.waitForFunction(()=>document.getElementById('strength_3d').data.find(t=>t.name==='GBP').visible==='legendonly');
 await page.locator('[data-legend-currency="GBP"]').click();await page.waitForFunction(()=>document.getElementById('strength_3d').data.find(t=>t.name==='GBP').visible===true);
 console.log('3D legend toggles: PASS');
 console.log('3D traces:',await page.evaluate(()=>document.getElementById('strength_3d').data.map(trace=>({name:trace.name,type:trace.type,points:trace.x.length}))));
 await page.screenshot({path:path.join(out,'refined-3d.png')});
 await page.locator('input[name=chart_dimension][value="2d"]').check({force:true});
 await page.locator('#theme_toggle').click();await page.waitForTimeout(500);await page.screenshot({path:path.join(out,'refined-explore-light.png')});
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForSelector('#comparison_chart canvas',{timeout:30000});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 assert.equal(await page.locator('#tab_data').isVisible(),true);
 await page.screenshot({path:path.join(out,'refined-mobile-explore.png'),fullPage:true});
 await page.locator('#tab_convert').click();await page.waitForSelector('.conversion-value');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.screenshot({path:path.join(out,'refined-mobile-convert.png'),fullPage:true});
 await page.locator('#tab_data').click();await page.waitForSelector('#summary_table tbody tr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await page.screenshot({path:path.join(out,'refined-mobile-data.png'),fullPage:true});
 await page.locator('#tab_explore').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab_convert').getAttribute('aria-selected'),'true');console.log('Keyboard tabs + 390px responsive views: PASS');
 await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),375);
 await page.setViewportSize({width:844,height:390});assert.equal(await page.evaluate(()=>document.getElementById('settings_panel').open),true);
 await page.evaluate(()=>document.getElementById('currencies').selectize.setValue([]));await page.waitForFunction(()=>document.querySelector('#data_notice')?.textContent.includes('Choose at least one'));
 await page.locator('#tab_data').click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.shiny-output-error-validation')).some(node=>node.textContent.includes('No comparison data')));
 console.log('375px + landscape + empty-selection handling: PASS');
 assert.deepEqual(errors,[]);assert.equal(await page.locator('.shiny-output-error:not(.shiny-output-error-validation)').count(),0);
 console.log('No browser or unexpected output errors: PASS');await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
