eu_icon <- function(name, size = 20) {
  paths <- switch(name,
    globe = '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z"/>',
    moon = '<path d="M20 13A8 8 0 0 1 11 4a8 8 0 1 0 9 9Z"/>',
    sun = '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/>',
    refresh = '<path d="M20 7v5h-5M4 17v-5h5M5.5 7a7.5 7.5 0 0 1 12-2L20 8M4 16l2.5 3a7.5 7.5 0 0 0 12-2"/>',
    arrow = '<path d="M5 12h14m-6-6 6 6-6 6"/>',
    swap = '<path d="M4 7h16m-4-4 4 4-4 4M20 17H4m4-4-4 4 4 4"/>',
    down = '<path d="M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6"/>',
    expand = '<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
    pin = '<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
    chart = '<path d="M4 3v17h17M7 14l4-5 4 3 6-8"/>',
    settings = '<path d="M4 7h6m4 0h6M4 17h10m4 0h2"/><circle cx="12" cy="7" r="2"/><circle cx="16" cy="17" r="2"/>',
    save = '<path d="M5 3h14v18l-7-4-7 4V3Z"/>',
    link = '<path d="m10 14 4-4m-6 6-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 0 2-2a4 4 0 1 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(2 -1)"/>',
    info = '<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',
    music = '<path d="M9 18V5l12-2v13M9 8l12-2"/><ellipse cx="6" cy="18" rx="3" ry="2.5"/><ellipse cx="18" cy="16" rx="3" ry="2.5"/>',
    pause = '<path d="M8 4v16M16 4v16"/>',
    check = '<path d="m4 12 5 5L20 6"/>',
    close = '<path d="m6 6 12 12M6 18 18 6"/>',
    '<circle cx="12" cy="12" r="9"/>')
  htmltools::HTML(sprintf('<svg width="%s" height="%s" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">%s</svg>', size, size, paths))
}

currency_options <- function(multiple = FALSE, removable = FALSE) {
  item <- if (removable) "function(item,escape){return '<div>'+escape(item.value)+'<button type=\"button\" class=\"remove\" aria-label=\"Remove '+escape(item.value)+'\">×</button></div>'; }" else if (multiple)
    "function(item,escape){return '<div>'+escape(item.value)+'</div>'; }" else
    "function(item,escape){var name=item.label.split(' · ')[1].split(' — ')[0];return '<div>'+escape(item.value)+' · '+escape(name)+'</div>'; }"
  option <- "function(item,escape){var parts=item.label.split(' — ');var name=parts[0].split(' · ').slice(1).join(' · ')||item.value;var places=parts[1]||'No current country mapping';return '<div class=\"currency-option\"><strong><span class=\"option-code\">'+escape(item.value)+'</span><span class=\"option-name\">'+escape(name)+'</span></strong><small>'+escape(places)+'</small></div>'; }"
  list(placeholder = "Search currencies…", render = I(paste0("{item:", item, ",option:", option, "}")))
}

icon_action <- function(id, label, icon, class = "quiet-button", ...) {
  shiny::actionButton(id, label = htmltools::tagList(eu_icon(icon), shiny::tags$span(label)), class = class, ...)
}

make_ui <- function(choices) {
  shiny::fluidPage(
    theme = bslib::bs_theme(version = 5, bg = "#E8E5DD", fg = "#243A38", primary = "#21655E",
                           base_font = "system-ui", bootswatch = NULL),
    shiny::tags$head(
      shiny::tags$title("Exchange Universe — Currency explorer"),
      shiny::tags$meta(name = "description", content = "Compare global currencies, convert amounts and explore exchange rates on an interactive world map."),
      shiny::tags$link(rel = "icon", type = "image/svg+xml", href = "favicon.svg"),
      shiny::tags$link(rel = "icon", type = "image/png", sizes = "32x32", href = "favicon-32.png"),
      shiny::tags$link(rel = "apple-touch-icon", sizes = "180x180", href = "apple-touch-icon.png"),
      shiny::tags$meta(name = "theme-color", content = "#101D32"),
      shiny::tags$meta(property = "og:title", content = "Exchange Universe — A currency atlas"),
      shiny::tags$meta(property = "og:description", content = "Compare currencies through time and place. Explore a world atlas, convert amounts and inspect the data."),
      shiny::tags$meta(property = "og:type", content = "website"),
      shiny::tags$meta(property = "og:image", content = paste0(sub("/$", "", Sys.getenv("EXCHANGE_PUBLIC_URL", "https://sadeq.shinyapps.io/exchange_universe")), "/social-preview.png")),
      shiny::tags$meta(property = "og:image:width", content = "1200"),
      shiny::tags$meta(property = "og:image:height", content = "630"),
      shiny::tags$meta(property = "og:image:alt", content = "Exchange Universe: currency comparison, conversion and a world atlas."),
      shiny::tags$meta(name = "twitter:card", content = "summary_large_image"),
      shiny::tags$link(rel = "stylesheet", href = "app.css"),
      shiny::tags$link(rel = "preload", href = "fonts/Inter-latin.woff2", as = "font", type = "font/woff2", crossorigin = "anonymous"),
      shiny::tags$link(rel = "preload", href = "fonts/FacultyGlyphic-latin.woff2", as = "font", type = "font/woff2", crossorigin = "anonymous"),
      shiny::tags$script(htmltools::HTML("try{var t=localStorage.getItem('exchange-universe.v2.theme');if(t==='dark'||t==='light')document.documentElement.dataset.theme=t;}catch(e){}")),
      shiny::tags$link(rel = "stylesheet", href = "orbital.css"),
      shiny::tags$script(src = "analytics.js", defer = "defer"),
      shiny::tags$script(src = "app.js", defer = "defer")
    ),
    shiny::tags$a(class = "skip-link", href = "#workspace", "Skip to currency workspace"),
    shiny::tags$header(class = "app-header",
      shiny::tags$a(class = "brand", href = "#explore", `data-workspace-view` = "explore", `aria-label` = "Exchange Universe home",
        shiny::tags$span(class = "brand-mark", shiny::tags$img(src = "logo-mark.svg", alt = "", width = 44, height = 44)),
        shiny::tags$span(shiny::tags$strong("Exchange Universe"), shiny::tags$small("A currency atlas"))),
      shiny::tags$nav(class = "top-nav", `aria-label` = "Workspace views",
        shiny::tags$div(role = "tablist", `aria-label` = "Currency workspace",
          lapply(c("explore", "convert", "data"), function(view) shiny::tags$button(id = paste0("tab_", view),
            type = "button", role = "tab", `aria-selected` = if (view == "explore") "true" else "false",
            `aria-controls` = paste0("view_", view), tabindex = if (view == "explore") "0" else "-1",
            `data-workspace-view` = view, class = if (view == "explore") "active" else "",
            switch(view, explore = "Explore", convert = "Convert", data = "Data"))))),
      shiny::tags$div(class = "header-actions",
        shiny::uiOutput("header_status", inline = TRUE),
        shiny::tags$button(id = "mobile_settings_toggle", class = "icon-button mobile-settings-toggle", type = "button",
          `aria-label` = "Open comparison settings", `aria-controls` = "mobile_settings_dialog", `aria-haspopup` = "dialog", eu_icon("settings"), shiny::tags$span("Settings")),
        shiny::tags$button(id = "theme_toggle", class = "icon-button", type = "button",
                           `aria-label` = "Switch to dark theme", eu_icon("moon")),
        shiny::tags$button(id = "music_toggle", class = "icon-button", type = "button",
          `aria-label` = "Play music", `aria-pressed` = "false", title = "Play music · 25 12 2021",
          shiny::tags$span(class = "music-idle", eu_icon("music")), shiny::tags$span(class = "music-playing", hidden = "hidden", eu_icon("pause"))),
        icon_action("about", "About", "info", "quiet-button about-button", `aria-label` = "About data and sources"))
    ),
    shiny::tags$div(class = "app-layout",
      shiny::tags$aside(class = "sidebar", tabindex = "0", `data-clarity-mask` = "true", `aria-label` = "Comparison settings; scroll independently",
        shiny::tags$details(id = "settings_panel", open = "open",
          shiny::tags$summary(class = "settings-summary", eu_icon("chart"), "Comparison settings"),
          shiny::tags$div(class = "settings-content",
            shiny::tags$details(id = "sidebar_currencies", class = "sidebar-section", open = "open",
            shiny::tags$summary("Currencies", shiny::tags$span(class = "collapse-mark", `aria-hidden` = "true")),
            shiny::tags$div(class = "sidebar-section-body",
            shiny::selectizeInput("base", "Base currency", choices, selected = "EUR", options = currency_options()),
            shiny::tags$p(class = "field-help", id = "base_help", "All rates are quoted per 1 unit of this currency."),
            shiny::selectizeInput("currencies", "Compare with", choices, selected = c("USD", "HUF", "GBP"), multiple = TRUE,
              options = c(currency_options(TRUE, removable = TRUE), list(maxItems = 6, closeAfterSelect = TRUE))),
            shiny::tags$p(class = "field-help", id = "compare_help", "Up to 6 currencies. Search by code, name or country."))),
            shiny::tags$details(id = "sidebar_period", class = "sidebar-section",
            shiny::tags$summary("Time period", shiny::tags$span(class = "collapse-mark", `aria-hidden` = "true")),
            shiny::tags$div(class = "sidebar-section-body",
            shiny::selectInput("period", "Time period", c("Last 30 days" = "30", "Last 90 days" = "90", "Last 6 months" = "180", "Last year" = "365", "Custom range" = "custom"), selected = "30", selectize = FALSE),
            shiny::conditionalPanel("input.period == 'custom'",
              shiny::tags$fieldset(class = "native-date-range",
                shiny::tags$legend("Date range"),
                shiny::tags$label(`for` = "dates_start", "Start date"),
                shiny::tags$input(id = "dates_start", name = "dates_start", type = "date", class = "form-control",
                  value = as.character(Sys.Date() - 30), min = "1999-01-01", max = as.character(Sys.Date())),
                shiny::tags$label(`for` = "dates_end", "End date"),
                shiny::tags$input(id = "dates_end", name = "dates_end", type = "date", class = "form-control",
                  value = as.character(Sys.Date()), min = "1999-01-01", max = as.character(Sys.Date())))),
            shiny::uiOutput("period_label"))),
            shiny::tags$details(id = "sidebar_saved", class = "sidebar-section",
            shiny::tags$summary("Saved views", shiny::tags$span(class = "collapse-mark", `aria-hidden` = "true")),
            shiny::tags$div(class = "sidebar-section-body",
            shiny::selectInput("saved_view", "Your saved views", choices = c("Choose a saved view…" = ""), selectize = FALSE),
            shiny::tags$div(class = "saved-actions", icon_action("save_view", "Save view", "save"),
                            icon_action("delete_view", "Remove", "refresh")),
            shiny::tags$p(class = "field-help", "Saved in this browser."))),
            shiny::tags$div(class = "sidebar-tip", eu_icon("pin"), shiny::tags$p("Click a country on the map to discover its currency and add it to your comparison.")))
        )
      ),
      shiny::tags$main(id = "workspace", class = "workspace", tabindex = "-1",
        shiny::tags$div(class = "intro-row",
          shiny::tags$div(shiny::tags$div(class = "eyebrow", "THE WORLD, IN CURRENCIES"),
            shiny::tags$h1(id = "workspace_title", "Value, across borders."),
            shiny::tags$p(id = "workspace_description", class = "intro-copy", "Compare currencies through time and place. Click a country to add its currency.")),
          shiny::tags$div(class = "intro-actions", icon_action("share", "Share", "link"), icon_action("refresh", "Refresh rates", "refresh"))),
        shiny::uiOutput("data_notice"),
        shiny::tags$div(id = "view_explore", class = "workspace-view", role = "tabpanel", `aria-labelledby` = "tab_explore",
        shiny::tags$div(id = "rate_cards", class = "shiny-html-output",
          shiny::tags$div(class = "rate-cards", `data-count` = "3", `aria-hidden` = "true",
            lapply(c("GBP", "HUF", "USD"), function(code) shiny::tags$article(class = "rate-card rate-placeholder",
              shiny::tags$div(class = "rate-card-top", shiny::tags$strong(class = "currency-code", code)),
              shiny::tags$div(class = "rate-value", "—"),
              shiny::tags$div(class = "rate-card-bottom", "Loading rates…"))))),
        shiny::tags$div(class = "analysis-grid",
          shiny::tags$section(id = "comparison_panel", class = "panel chart-panel", `aria-labelledby` = "chart_heading",
            shiny::tags$div(class = "panel-heading",
              shiny::tags$div(shiny::tags$div(class = "eyebrow", "01 / COMPARE"), shiny::tags$h2(id = "chart_heading", "Currency movement")),
              shiny::tags$div(class = "chart-tools",
                shiny::radioButtons("chart_dimension", "Chart dimensions", c("2D" = "2d", "3D" = "3d"), inline = TRUE, selected = "2d"),
                shiny::tags$button(type = "button", class = "icon-button", `data-fullscreen-panel` = "comparison_panel", `aria-label` = "Expand currency movement plot", eu_icon("expand")),
                shiny::tags$button(type = "button", class = "icon-button", `data-export-chart` = "comparison_chart", `aria-label` = "Download chart as PNG", eu_icon("down")))),
            shiny::radioButtons("metric", "Chart measure", c("Change %" = "performance", "Exchange rate" = "rate"), selected = "performance", inline = TRUE),
            shiny::conditionalPanel("input.chart_dimension == '3d'", class = "three-d-controls",
              shiny::tags$span("Drag to rotate · Wheel / pinch to zoom"),
              shiny::tags$div(class = "figure-controls",
                shiny::tags$button(type = "button", class = "icon-button", `data-zoom-3d` = "in", `aria-label` = "Zoom in 3D plot", "+"),
                shiny::tags$button(type = "button", class = "icon-button", `data-zoom-3d` = "out", `aria-label` = "Zoom out 3D plot", "−"),
                shiny::tags$button(type = "button", class = "quiet-button", `data-zoom-3d` = "reset", "Reset view"))),
            shiny::conditionalPanel("input.chart_dimension != '3d'", class = "chart-two-d",
            shiny::tags$div(class = "chart-wrap", echarts4r::echarts4rOutput("comparison_chart", height = "350px"))),
            shiny::uiOutput("three_d_slot"),
            shiny::uiOutput("chart_legend"), shiny::uiOutput("chart_caption"),
            shiny::tags$details(class = "chart-accessible", shiny::tags$summary("Exact chart values"),
              shiny::tableOutput("chart_values"))
          ),
          shiny::tags$section(id = "map_panel", class = "panel map-panel", `aria-labelledby` = "map_heading",
            shiny::tags$div(class = "panel-heading",
              shiny::tags$div(shiny::tags$div(class = "eyebrow", "02 / LOCATE"), shiny::tags$h2(id = "map_heading", "The currency atlas")),
              shiny::tags$button(type = "button", id = "map_fullscreen", class = "icon-button", `data-fullscreen-panel` = "map_panel", `aria-label` = "Expand world map", eu_icon("expand"))),
            shiny::tags$div(class = "map-toolbar", shiny::selectInput("map_mode", "Map coloring", c("Currency locations" = "locations", "Period change" = "change"), selectize = FALSE),
              icon_action("fit_map", "Fit selection", "pin"),
              icon_action("clear_map", "Clear", "close", "icon-button", `aria-label` = "Clear country selections from map", title = "Clear map selections")),
            shiny::tags$div(class = "map-wrap", leaflet::leafletOutput("world_map", height = "350px")),
            shiny::uiOutput("map_legend"),
            shiny::tags$div(class = "map-date", shiny::tags$span(id = "observation_label", "Observation date"),
              shiny::uiOutput("observation_input", inline = TRUE))
          )
        ),
        shiny::tags$section(class = "atlas-details", `aria-label` = "Country details and search",
          shiny::uiOutput("country_detail"),
          shiny::tags$details(class = "country-search", shiny::tags$summary("Find a country or territory"),
            shiny::selectizeInput("country_search", "Country / territory", choices = NULL, selected = "", options = list(placeholder = "Search places…")))),
        shiny::tags$section(id = "change_panel", class = "panel change-panel", `aria-labelledby` = "change_heading",
          shiny::tags$div(class = "panel-heading", shiny::tags$div(shiny::tags$div(class = "eyebrow", "PERIOD SNAPSHOT"), shiny::tags$h2(id = "change_heading", "Strength against the base")),
            shiny::tags$div(class = "figure-controls",
              shiny::tags$button(type = "button", class = "icon-button", `data-fullscreen-panel` = "change_panel", `aria-label` = "Expand strength snapshot plot", eu_icon("expand")),
              shiny::tags$button(type = "button", class = "icon-button", `data-export-chart` = "change_chart", `aria-label` = "Download strength snapshot as PNG", eu_icon("down")),
              shiny::tags$button(type = "button", class = "quiet-button", `data-workspace-view` = "data", "Inspect detailed data", eu_icon("arrow", 16)))),
          echarts4r::echarts4rOutput("change_chart", height = "170px"),
          shiny::tags$p(class = "panel-caption", "Positive means the selected currency strengthened against your base."))),
        shiny::tags$div(id = "view_convert", class = "workspace-view", role = "tabpanel", `aria-labelledby` = "tab_convert", hidden = "hidden",
        shiny::tags$div(class = "conversion-grid",
          shiny::tags$section(id = "converter", class = "panel converter-panel", `data-clarity-mask` = "true", `aria-labelledby` = "converter_heading",
            shiny::tags$div(class = "panel-heading", shiny::tags$div(shiny::tags$div(class = "eyebrow", "01 / CALCULATE"), shiny::tags$h2(id = "converter_heading", "Make the exchange")), eu_icon("swap", 24)),
            shiny::tags$div(class = "converter-fields", shiny::numericInput("amount", "Amount", value = 1000, min = 0, max = 1e12, step = 1),
              shiny::selectizeInput("from", "From", choices, selected = "EUR", options = currency_options(TRUE)),
              icon_action("swap", "Swap", "swap", "icon-button swap-button", `aria-label` = "Swap source and target currencies"),
              shiny::selectizeInput("to", "To", choices, selected = "HUF", options = currency_options(TRUE))),
            shiny::tags$div(class = "amount-presets", shiny::tags$span("Quick amounts"), lapply(c(100, 1000, 10000), function(value)
              shiny::tags$button(type = "button", class = "quiet-button", `data-amount` = value, format(value, big.mark = ",", scientific = FALSE)))),
            shiny::uiOutput("conversion_result"), shiny::uiOutput("conversion_note")),
          shiny::tags$section(class = "panel quote-context", `aria-labelledby` = "quote_heading",
            shiny::tags$div(class = "panel-heading", shiny::tags$div(shiny::tags$div(class = "eyebrow", "02 / UNDERSTAND"), shiny::tags$h2(id = "quote_heading", "Before you exchange"))),
            shiny::uiOutput("quote_context"),
            shiny::tags$p(class = "panel-caption", "These are indicative reference rates, not an offer from a bank. Fees and buy/sell spreads are not included."))),
        shiny::tags$section(class = "panel conversion-basket", `aria-labelledby` = "basket_heading",
          shiny::tags$div(class = "panel-heading", shiny::tags$div(shiny::tags$div(class = "eyebrow", "03 / COMPARE AMOUNTS"), shiny::tags$h2(id = "basket_heading", "Your amount, in every selected currency"))),
          shiny::uiOutput("conversion_basket"))),
        shiny::tags$div(id = "view_data", class = "workspace-view", role = "tabpanel", `aria-labelledby` = "tab_data", hidden = "hidden",
        shiny::tags$section(id = "data-section", class = "panel data-panel", `aria-labelledby` = "data_heading",
          shiny::tags$div(class = "panel-heading", shiny::tags$div(shiny::tags$div(class = "eyebrow", "01 / INSPECT"), shiny::tags$h2(id = "data_heading", "The numbers behind the view")),
            shiny::downloadButton("download_csv", label = "Export CSV", class = "quiet-button")),
          shiny::tags$div(class = "data-toolbar",
            shiny::radioButtons("data_mode", "Data set", c("Comparison details" = "summary", "Daily history" = "history", "All current quotes" = "quotes"), inline = TRUE),
            shiny::uiOutput("data_stats")),
          shiny::tags$div(class = "table-navigation",
            shiny::tags$p(id = "table_scroll_help", "More columns to the right. Wheel sideways, or hold Shift + wheel. Arrow keys work when the table is focused."),
            shiny::tags$div(class = "table-arrows",
              shiny::tags$button(type = "button", class = "icon-button", `data-table-scroll` = "-1", `aria-label` = "Scroll data table left", eu_icon("arrow")),
              shiny::tags$button(type = "button", class = "icon-button", `data-table-scroll` = "1", `aria-label` = "Scroll data table right", eu_icon("arrow")))),
          shiny::tags$div(class = "table-scroll", shiny::uiOutput("data_table_slot")),
          shiny::uiOutput("table_caption")),
        shiny::tags$section(class = "data-definitions", `aria-labelledby` = "definitions_heading",
          shiny::tags$h2(id = "definitions_heading", "Read the numbers correctly"),
          shiny::tags$div(class = "definition-grid",
            shiny::tags$div(shiny::tags$strong("Quote direction"), shiny::tags$p("Every rate is units of the quoted currency per 1 base currency. The inverse reverses that direction.")),
            shiny::tags$div(shiny::tags$strong("Strength vs. rate"), shiny::tags$p("Strength % = (start-date rate ÷ observed rate − 1) × 100. Positive means the quoted currency strengthened.")),
            shiny::tags$div(shiny::tags$strong("Real observations"), shiny::tags$p("Daily history is not hourly data. The latest day can be a timestamped indicative snapshot. Missing values are never filled with invented rates."))))),
        shiny::tags$footer(id = "app_footer", class = "workspace-footer", shiny::uiOutput("source_footer"),
          shiny::tags$span("Indicative exchange rates. Your bank’s quote may differ."),
          shiny::tags$div(class = "footer-credit", "Designed & built by ",
            shiny::tags$a(href = "https://rammeshgar.github.io/", target = "_blank", rel = "noopener", "Sadeq Rezai"),
            shiny::tags$button(type = "button", class = "text-button", `data-privacy-open` = "true", "Privacy settings")))
      )
    ),
    shiny::tags$dialog(id = "mobile_settings_dialog", `aria-labelledby` = "mobile_settings_title",
      shiny::tags$div(class = "mobile-settings-heading",
        shiny::tags$h2(id = "mobile_settings_title", tabindex = "-1", "Your workspace"),
        shiny::tags$button(type = "button", class = "icon-button", `data-toggle-theme` = "true", `aria-label` = "Switch theme", eu_icon("sun")),
        shiny::tags$button(type = "button", class = "quiet-button", `data-mobile-settings-close` = "true", "Done", eu_icon("close", 16)))),
    shiny::tags$dialog(id = "figure_dialog", `aria-labelledby` = "figure_dialog_title",
      shiny::tags$div(class = "figure-dialog-heading", shiny::tags$h2(id = "figure_dialog_title", tabindex = "-1", "Expanded figure"),
        shiny::tags$button(type = "button", class = "quiet-button", `data-figure-close` = "true", "Close", eu_icon("close", 16)))),
    shiny::tags$dialog(id = "privacy_dialog", `aria-labelledby` = "privacy_title",
      shiny::tags$div(class = "figure-dialog-heading", shiny::tags$h2(id = "privacy_title", tabindex = "-1", "Privacy settings"),
        shiny::tags$button(type = "button", class = "quiet-button", `data-privacy-close` = "true", "Close")),
      shiny::tags$div(class = "privacy-body",
        shiny::tags$p(id = "analytics_status", role = "status"),
        shiny::tags$p("Google Analytics (GA4) and Microsoft Clarity tags load automatically on the public app unless you previously disabled them. Without an explicit allowance, cookie consent remains denied and provider collection may be restricted. Advertising consent remains denied. Local previews never load either service."),
        shiny::tags$p("Comparison settings and amounts are masked for Clarity. GA4 receives the app path, not comparison query parameters. Theme and saved views stay in your browser independently of analytics."),
        shiny::tags$p("Your analytics choice is saved in this browser for up to six months. You can change it here. Withdrawal reloads the page to stop the loaded trackers."),
        shiny::tags$p(shiny::tags$a(href = "https://policies.google.com/privacy", target = "_blank", rel = "noopener", "Google privacy policy"), " · ",
          shiny::tags$a(href = "https://privacy.microsoft.com/privacystatement", target = "_blank", rel = "noopener", "Microsoft privacy statement")),
        shiny::tags$div(class = "consent-actions",
          shiny::tags$button(type = "button", class = "quiet-button", `data-analytics-consent` = "denied", "Decline / withdraw"),
          shiny::tags$button(type = "button", class = "quiet-button", `data-analytics-consent` = "granted", "Allow analytics")))),
    shiny::tags$audio(id = "ambient_music", preload = "none", `data-src` = "audio/25-12-2021.mp3"),
    shiny::tags$div(id = "local_toast", class = "local-toast", role = "status", `aria-live` = "polite")
  )
}
